Traceback (most recent call last):
  File "/home/lihkir/PythonEnvs/ml_venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/lihkir/PythonEnvs/ml_venv/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/lihkir/PythonEnvs/ml_venv/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/lihkir/PythonEnvs/ml_venv/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/lihkir/PythonEnvs/ml_venv/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/lihkir/PythonEnvs/ml_venv/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/lihkir/PythonEnvs/ml_venv/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# grafico de dispersi√≥n con las variables mencionadas para el an√°lisis
import plotly.express as px 
  
df = px.data.iris() 
  
fig = px.scatter_3d(df, x = 'sepal_width',  
                    y = 'sepal_length',  
                    z = 'petal_width')#,
                   # color = 'species') 

fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [16][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# grafico de dispersi√≥n con las variables mencionadas para el an√°lisis[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mexpress[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpx[39;00m 
[1;32m      4[0m df [38;5;241m=[39m px[38;5;241m.[39mdata[38;5;241m.[39miris() 
[1;32m      6[0m fig [38;5;241m=[39m px[38;5;241m.[39mscatter_3d(df, x [38;5;241m=[39m [38;5;124m'[39m[38;5;124msepal_width[39m[38;5;124m'[39m,  
[1;32m      7[0m                     y [38;5;241m=[39m [38;5;124m'[39m[38;5;124msepal_length[39m[38;5;124m'[39m,  
[1;32m      8[0m                     z [38;5;241m=[39m [38;5;124m'[39m[38;5;124mpetal_width[39m[38;5;124m'[39m)[38;5;66;03m#,[39;00m

[0;31mModuleNotFoundError[0m: No module named 'plotly'
ModuleNotFoundError: No module named 'plotly'

